server:
  display-name: WS-TEST
  port: 8009
  error:
    whitelabel:
      enabled: false
  compression:
    min-response-size: 512
    enabled: true
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg