###################  项目启动端口  ###################
server:
  display-name: WS-TEST
  port: 8009
  error:
    whitelabel:
      enabled: false
  compression:
    min-response-size: 512 #压缩文件最小大小(kb)
    enabled: true #是否压缩
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg #要压缩的文件格式